## Please see https://github.com/aczw/sddm-theme-corners/blob/main/CONFIG.md for
## more information about these options. Happy configuring!

[General]

# BgSource:     string. Path to an image, used as the wallpaper. Can be placed
#               in the `backgrounds/` folder for convenience (see below!)
#
# FontFamily:   string. Name of the font family. You can find this with
#               something like `fontconfig`, for example.
#
# FontSize:     number. This value is used for everything *except* the date/time.
#
# Padding:      number. How far away things should be from the edge of your screen.
#
# Radius:       number. Corner radius for UI. Set to 0 to disable rounded corners.
#
# Scale:        number. Adjusts the size of UI elements. Can be anything, but I
#               would stick between 1 and 2 (e.g. 1.5).

BgSource="/usr/share/sddm/themes/corners/backgrounds/MIKA.PNG"
FontFamily="Atkinson Hyperlegible"
FontSize=9
Padding=50
Radius=10
Scale=1

# User picture

UserPictureEnabled=false
UserBorderWidth=5
UserBorderColor="#a98f80"
UserColor="#d8c8bc"

# Input fields

InputColor="#211f1e"
InputTextColor="#d8c8bc"
InputBorderWidth=4
InputBorderColor="#a98f80"
UserPlaceholderText="user"
PassPlaceholderText="password"
HidePassword=true

# Login button

LoginButtonTextColor="#211f1e"
LoginButtonText="Login"
LoginButtonColor="#c4ad9e"

# Popup

PopupColor="#a98f80"
PopupActiveColor="#211f1e"
PopupActiveTextColor="#e8ddd5"

# Session and power buttons

SessionButtonColor="#c4ad9e"
SessionIconColor="#211f1e"
PowerButtonColor="#c4ad9e"
PowerIconColor="#211f1e"

# Date and time

DateTimeSpacing=-20

DateColor="#d8c8bc"
DateSize=36
DateIsBold=false
DateOpacity=1.0
DateFormat="dddd, MMMM d"

TimeColor="#eee5df"
TimeSize=48
TimeIsBold=true
TimeOpacity=1.0
TimeFormat="hh:mm AP"
