[General]
BgSource="/usr/share/sddm/themes/corners/backgrounds/background3"
FontFamily="Atkinson Hyperlegible"
FontSize=9
Padding=50
Radius=10
Scale=1

UserPictureEnabled=false
UserBorderWidth=5
UserBorderColor="#D9DDE8"
UserColor="#E5E8F0"

InputColor="#F4F6FB"
InputTextColor="#2A2D3A"
InputBorderWidth=3
InputBorderColor="#E8B4B8"

UserPlaceholderText="user"
PassPlaceholderText="password"
HidePassword=true

LoginButtonTextColor="#FFFFFF"
LoginButtonText="Login"
LoginButtonColor="#E8B4B8"

PopupColor="#EDEFF6"
PopupActiveColor="#E8B4B8"
PopupActiveTextColor="#FFFFFF"

SessionButtonColor="#AEB9D6"
SessionIconColor="#F6F4F3"
PowerButtonColor="#AEB9D6"
PowerIconColor="#F6F4F3"

DateTimeSpacing=-20
DateColor="#E8B4B8"
DateSize=36
DateIsBold=true
DateOpacity=1.0
DateFormat="dddd, MMMM d"

TimeColor="#E8B4B8"
TimeSize=48
TimeIsBold=true
TimeOpacity=1.0
TimeFormat="hh:mm AP"
